# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83720ca9191a9089596305dc587ab8351cf96665f50e9068769e116fb4458a61db964dd9974613c4bea9a1556975f238ccf452519dcdc9ece15b5f0ddb2efe6

test:
  secret_key_base: 0a3afe409f586c5af85053b950afb9c09c2a6fbd2da46796a015f3dd09b0ed7bd0d2b54e9487f84f473652dc2a83d490bae775f6a68c00afc9f919f2db65f439

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
